export const UPDATE_PLANIMETRY_FORM = 'UPDATE_PLANIMETRY_FORM'
export const CLEAR_FORM = 'CLEAR_FORM'

export const ADD_FORM_TO_TABLE = 'ADD_FORM_TO_TABLE'

export const CALCULATE_CORRETION = 'CALCULATE_CORRETION'

export default {
    UPDATE_PLANIMETRY_FORM,
    ADD_FORM_TO_TABLE,
    CLEAR_FORM,
    CALCULATE_CORRETION,
}